/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kylie Stockberger (https://sketchfab.com/ZeldaLilly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-777-airplane-43847f1a45ff43b180955dfd0cce3f19
Title: Boeing 777 Airplane
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    polySurface52_Main_Body_0: THREE.Mesh;
    polySurface67_WingExtrasColors_0: THREE.Mesh;
    polySurface68_WingExtrasColors_0: THREE.Mesh;
    polySurface69_WingExtrasColors_0: THREE.Mesh;
    polySurface64_WingExtrasColors_0: THREE.Mesh;
    polySurface65_WingExtrasColors_0: THREE.Mesh;
    polySurface66_WingExtrasColors_0: THREE.Mesh;
    polySurface70_Engines_0: THREE.Mesh;
    polySurface71_WingExtrasColors_0: THREE.Mesh;
    polySurface73_WingExtrasColors_0: THREE.Mesh;
    polySurface74_Engines_0: THREE.Mesh;
  };
  materials: {
    Main_Body: THREE.MeshStandardMaterial;
    WingExtrasColors: THREE.MeshStandardMaterial;
    Engines: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/airplane.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0, -2396.37182617]}
        rotation={[-Math.PI, 0, Math.PI]}
        scale={[-1, 1, 1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface64_WingExtrasColors_0.geometry}
          material={materials.WingExtrasColors}
          position={[328.69619751, 644.84570313, -1396.69970703]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface65_WingExtrasColors_0.geometry}
          material={materials.WingExtrasColors}
          position={[289.9329834, 644.84570313, -1396.69970703]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface66_WingExtrasColors_0.geometry}
          material={materials.WingExtrasColors}
          position={[240.27456665, 644.84570313, -1396.69970703]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface52_Main_Body_0.geometry}
        material={materials.Main_Body}
        position={[161.24238586, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface67_WingExtrasColors_0.geometry}
        material={materials.WingExtrasColors}
        position={[328.69619751, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_WingExtrasColors_0.geometry}
        material={materials.WingExtrasColors}
        position={[289.9329834, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_WingExtrasColors_0.geometry}
        material={materials.WingExtrasColors}
        position={[240.27456665, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_Engines_0.geometry}
        material={materials.Engines}
        position={[161.24238586, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface71_WingExtrasColors_0.geometry}
        material={materials.WingExtrasColors}
        position={[161.24238586, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface73_WingExtrasColors_0.geometry}
        material={materials.WingExtrasColors}
        position={[161.24238586, 644.84570313, 1396.69970703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface74_Engines_0.geometry}
        material={materials.Engines}
        position={[161.24238586, 645.69165039, 2308.16186523]}
      />
    </group>
  );
}

useGLTF.preload("/airplane.gltf");
